// Generated by scripts/gen_bazel_fixture.py. Do not edit.
#include "src/lib062.h"

#include "src/lib002.h"
#include "src/lib019.h"
#include "src/lib031.h"
#include <algorithm>
#include <array>
#include <numeric>
#include <sstream>

namespace ballast_lib062 {

template <int N, typename T>
struct Chain {
  static T apply(T x) {
    return Chain<N - 1, T>::apply(x * 6364136223846793005ULL + N) ^ (x >> 7);
  }
};
template <typename T>
struct Chain<0, T> {
  static T apply(T x) { return x; }
};

template <int Tag>
struct Tagged {
  std::uint64_t v;
  std::array<std::uint64_t, 4> pad;
};

template <int Tag>
std::uint64_t sortmix(std::uint64_t x) {
  std::array<Tagged<Tag>, 24> a{};
  for (int i = 0; i < 24; ++i) {
    a[i].v = Chain<8, std::uint64_t>::apply(x + i + Tag);
  }
  std::sort(a.begin(), a.end(),
            [](const Tagged<Tag>& p, const Tagged<Tag>& q) { return p.v < q.v; });
  return a[0].v ^ a[23].v;
}

std::uint64_t f0(std::uint64_t x) { return sortmix<0>(x) + 1463987304ULL; }
std::uint64_t f1(std::uint64_t x) { return sortmix<1>(x) + 3894399054ULL; }
std::uint64_t f2(std::uint64_t x) { return sortmix<2>(x) + 884334094ULL; }
std::uint64_t f3(std::uint64_t x) { return sortmix<3>(x) + 4125946715ULL; }
std::uint64_t f4(std::uint64_t x) { return sortmix<4>(x) + 1210873379ULL; }
std::uint64_t f5(std::uint64_t x) { return sortmix<5>(x) + 241431542ULL; }
std::uint64_t f6(std::uint64_t x) { return sortmix<6>(x) + 2472858106ULL; }
std::uint64_t f7(std::uint64_t x) { return sortmix<7>(x) + 3153309013ULL; }
std::uint64_t f8(std::uint64_t x) { return sortmix<8>(x) + 673538585ULL; }
std::uint64_t f9(std::uint64_t x) { return sortmix<9>(x) + 3980189114ULL; }
std::uint64_t f10(std::uint64_t x) { return sortmix<10>(x) + 3295173097ULL; }
std::uint64_t f11(std::uint64_t x) { return sortmix<11>(x) + 2851095907ULL; }
std::uint64_t f12(std::uint64_t x) { return sortmix<12>(x) + 1071443318ULL; }
std::uint64_t f13(std::uint64_t x) { return sortmix<13>(x) + 1926470785ULL; }
std::uint64_t f14(std::uint64_t x) { return sortmix<14>(x) + 3563142406ULL; }
std::uint64_t f15(std::uint64_t x) { return sortmix<15>(x) + 3429639714ULL; }
std::uint64_t f16(std::uint64_t x) { return sortmix<16>(x) + 566999442ULL; }
std::uint64_t f17(std::uint64_t x) { return sortmix<17>(x) + 1767390785ULL; }
std::uint64_t f18(std::uint64_t x) { return sortmix<18>(x) + 3092187084ULL; }
std::uint64_t f19(std::uint64_t x) { return sortmix<19>(x) + 1771507233ULL; }
std::uint64_t f20(std::uint64_t x) { return sortmix<20>(x) + 1958891097ULL; }
std::uint64_t f21(std::uint64_t x) { return sortmix<21>(x) + 348389375ULL; }
std::uint64_t f22(std::uint64_t x) { return sortmix<22>(x) + 683070386ULL; }
std::uint64_t f23(std::uint64_t x) { return sortmix<23>(x) + 1563963657ULL; }
std::uint64_t f24(std::uint64_t x) { return sortmix<24>(x) + 1963855302ULL; }
std::uint64_t f25(std::uint64_t x) { return sortmix<25>(x) + 4003205241ULL; }
std::uint64_t f26(std::uint64_t x) { return sortmix<26>(x) + 797677398ULL; }
std::uint64_t f27(std::uint64_t x) { return sortmix<27>(x) + 3599560741ULL; }
std::uint64_t f28(std::uint64_t x) { return sortmix<28>(x) + 3524202704ULL; }
std::uint64_t f29(std::uint64_t x) { return sortmix<29>(x) + 1240646088ULL; }
std::uint64_t f30(std::uint64_t x) { return sortmix<30>(x) + 354256244ULL; }
std::uint64_t f31(std::uint64_t x) { return sortmix<31>(x) + 3959044307ULL; }
std::uint64_t f32(std::uint64_t x) { return sortmix<32>(x) + 118642558ULL; }
std::uint64_t f33(std::uint64_t x) { return sortmix<33>(x) + 4236999245ULL; }
std::uint64_t f34(std::uint64_t x) { return sortmix<34>(x) + 3636603502ULL; }
std::uint64_t f35(std::uint64_t x) { return sortmix<35>(x) + 3303336204ULL; }
std::uint64_t f36(std::uint64_t x) { return sortmix<36>(x) + 2828392258ULL; }
std::uint64_t f37(std::uint64_t x) { return sortmix<37>(x) + 3648807854ULL; }
std::uint64_t f38(std::uint64_t x) { return sortmix<38>(x) + 3522734530ULL; }
std::uint64_t f39(std::uint64_t x) { return sortmix<39>(x) + 3586313564ULL; }

inline std::uint64_t all(std::uint64_t x) {
  std::uint64_t a = x;
  a ^= f0(a);
  a ^= f1(a);
  a ^= f2(a);
  a ^= f3(a);
  a ^= f4(a);
  a ^= f5(a);
  a ^= f6(a);
  a ^= f7(a);
  a ^= f8(a);
  a ^= f9(a);
  a ^= f10(a);
  a ^= f11(a);
  a ^= f12(a);
  a ^= f13(a);
  a ^= f14(a);
  a ^= f15(a);
  a ^= f16(a);
  a ^= f17(a);
  a ^= f18(a);
  a ^= f19(a);
  a ^= f20(a);
  a ^= f21(a);
  a ^= f22(a);
  a ^= f23(a);
  a ^= f24(a);
  a ^= f25(a);
  a ^= f26(a);
  a ^= f27(a);
  a ^= f28(a);
  a ^= f29(a);
  a ^= f30(a);
  a ^= f31(a);
  a ^= f32(a);
  a ^= f33(a);
  a ^= f34(a);
  a ^= f35(a);
  a ^= f36(a);
  a ^= f37(a);
  a ^= f38(a);
  a ^= f39(a);
  return a;
}

}  // namespace ballast_lib062


namespace kilncache_bench {

Unit062::Unit062(std::uint64_t seed) : seed_(seed ^ 0x41b3f175c5c8b817ULL) {}

std::uint64_t Unit062::Mix(std::uint64_t value) const {
  std::uint64_t x = value ^ seed_;
  x ^= x >> 33;
  x *= 0xff51afd7ed558ccdULL;
  x ^= x >> 33;
  x *= 0xc4ceb9fe1a85ec53ULL;
  x ^= x >> 33;
  x ^= ballast_lib062::all(x);
  x ^= lib002_checksum(x);
  x ^= lib019_checksum(x);
  x ^= lib031_checksum(x);
  return x;
}

std::string Unit062::Describe() const {
  std::ostringstream out;
  out << "Unit062(seed=" << seed_ << ")";
  out << "+" << Unit002(seed_).Describe();
  return out.str();
}

std::vector<std::uint64_t> Unit062::Fold(const std::vector<std::uint64_t>& input) const {
  std::vector<std::uint64_t> result;
  result.reserve(input.size());
  for (std::uint64_t v : input) {
    result.push_back(Mix(v));
  }
  std::sort(result.begin(), result.end());
  return result;
}

std::uint64_t lib062_checksum(std::uint64_t value) {
  Unit062 instance(0x41b3f175c5c8b817ULL);
  return instance.Mix(value);
}

}  // namespace kilncache_bench
