// Generated by scripts/gen_bazel_fixture.py. Do not edit.
#include "src/lib079.h"

#include "src/lib041.h"
#include "src/lib051.h"
#include "src/lib061.h"
#include <algorithm>
#include <array>
#include <numeric>
#include <sstream>

namespace ballast_lib079 {

template <int N, typename T>
struct Chain {
  static T apply(T x) {
    return Chain<N - 1, T>::apply(x * 6364136223846793005ULL + N) ^ (x >> 7);
  }
};
template <typename T>
struct Chain<0, T> {
  static T apply(T x) { return x; }
};

template <int Tag>
struct Tagged {
  std::uint64_t v;
  std::array<std::uint64_t, 4> pad;
};

template <int Tag>
std::uint64_t sortmix(std::uint64_t x) {
  std::array<Tagged<Tag>, 24> a{};
  for (int i = 0; i < 24; ++i) {
    a[i].v = Chain<8, std::uint64_t>::apply(x + i + Tag);
  }
  std::sort(a.begin(), a.end(),
            [](const Tagged<Tag>& p, const Tagged<Tag>& q) { return p.v < q.v; });
  return a[0].v ^ a[23].v;
}

std::uint64_t f0(std::uint64_t x) { return sortmix<0>(x) + 2803545833ULL; }
std::uint64_t f1(std::uint64_t x) { return sortmix<1>(x) + 46359686ULL; }
std::uint64_t f2(std::uint64_t x) { return sortmix<2>(x) + 2563413244ULL; }
std::uint64_t f3(std::uint64_t x) { return sortmix<3>(x) + 723366700ULL; }
std::uint64_t f4(std::uint64_t x) { return sortmix<4>(x) + 2365656725ULL; }
std::uint64_t f5(std::uint64_t x) { return sortmix<5>(x) + 1845907487ULL; }
std::uint64_t f6(std::uint64_t x) { return sortmix<6>(x) + 1947341023ULL; }
std::uint64_t f7(std::uint64_t x) { return sortmix<7>(x) + 364284621ULL; }
std::uint64_t f8(std::uint64_t x) { return sortmix<8>(x) + 4218859457ULL; }
std::uint64_t f9(std::uint64_t x) { return sortmix<9>(x) + 2098698282ULL; }
std::uint64_t f10(std::uint64_t x) { return sortmix<10>(x) + 1786919059ULL; }
std::uint64_t f11(std::uint64_t x) { return sortmix<11>(x) + 1390960131ULL; }
std::uint64_t f12(std::uint64_t x) { return sortmix<12>(x) + 3718224120ULL; }
std::uint64_t f13(std::uint64_t x) { return sortmix<13>(x) + 1088566909ULL; }
std::uint64_t f14(std::uint64_t x) { return sortmix<14>(x) + 802513458ULL; }
std::uint64_t f15(std::uint64_t x) { return sortmix<15>(x) + 2797361920ULL; }
std::uint64_t f16(std::uint64_t x) { return sortmix<16>(x) + 1177677763ULL; }
std::uint64_t f17(std::uint64_t x) { return sortmix<17>(x) + 2856272886ULL; }
std::uint64_t f18(std::uint64_t x) { return sortmix<18>(x) + 2540081313ULL; }
std::uint64_t f19(std::uint64_t x) { return sortmix<19>(x) + 3308669873ULL; }
std::uint64_t f20(std::uint64_t x) { return sortmix<20>(x) + 214496045ULL; }
std::uint64_t f21(std::uint64_t x) { return sortmix<21>(x) + 903466577ULL; }
std::uint64_t f22(std::uint64_t x) { return sortmix<22>(x) + 401416922ULL; }
std::uint64_t f23(std::uint64_t x) { return sortmix<23>(x) + 171931954ULL; }
std::uint64_t f24(std::uint64_t x) { return sortmix<24>(x) + 2522945535ULL; }
std::uint64_t f25(std::uint64_t x) { return sortmix<25>(x) + 3364777787ULL; }
std::uint64_t f26(std::uint64_t x) { return sortmix<26>(x) + 3060454077ULL; }
std::uint64_t f27(std::uint64_t x) { return sortmix<27>(x) + 3414173738ULL; }
std::uint64_t f28(std::uint64_t x) { return sortmix<28>(x) + 2912635680ULL; }
std::uint64_t f29(std::uint64_t x) { return sortmix<29>(x) + 571383229ULL; }
std::uint64_t f30(std::uint64_t x) { return sortmix<30>(x) + 4041315247ULL; }
std::uint64_t f31(std::uint64_t x) { return sortmix<31>(x) + 2210120252ULL; }
std::uint64_t f32(std::uint64_t x) { return sortmix<32>(x) + 645484375ULL; }
std::uint64_t f33(std::uint64_t x) { return sortmix<33>(x) + 2812540636ULL; }
std::uint64_t f34(std::uint64_t x) { return sortmix<34>(x) + 3481077996ULL; }
std::uint64_t f35(std::uint64_t x) { return sortmix<35>(x) + 1267278026ULL; }
std::uint64_t f36(std::uint64_t x) { return sortmix<36>(x) + 4288745607ULL; }
std::uint64_t f37(std::uint64_t x) { return sortmix<37>(x) + 1862041703ULL; }
std::uint64_t f38(std::uint64_t x) { return sortmix<38>(x) + 3358179585ULL; }
std::uint64_t f39(std::uint64_t x) { return sortmix<39>(x) + 2391829705ULL; }

inline std::uint64_t all(std::uint64_t x) {
  std::uint64_t a = x;
  a ^= f0(a);
  a ^= f1(a);
  a ^= f2(a);
  a ^= f3(a);
  a ^= f4(a);
  a ^= f5(a);
  a ^= f6(a);
  a ^= f7(a);
  a ^= f8(a);
  a ^= f9(a);
  a ^= f10(a);
  a ^= f11(a);
  a ^= f12(a);
  a ^= f13(a);
  a ^= f14(a);
  a ^= f15(a);
  a ^= f16(a);
  a ^= f17(a);
  a ^= f18(a);
  a ^= f19(a);
  a ^= f20(a);
  a ^= f21(a);
  a ^= f22(a);
  a ^= f23(a);
  a ^= f24(a);
  a ^= f25(a);
  a ^= f26(a);
  a ^= f27(a);
  a ^= f28(a);
  a ^= f29(a);
  a ^= f30(a);
  a ^= f31(a);
  a ^= f32(a);
  a ^= f33(a);
  a ^= f34(a);
  a ^= f35(a);
  a ^= f36(a);
  a ^= f37(a);
  a ^= f38(a);
  a ^= f39(a);
  return a;
}

}  // namespace ballast_lib079


namespace kilncache_bench {

Unit079::Unit079(std::uint64_t seed) : seed_(seed ^ 0x8ff3a718b7e479a2ULL) {}

std::uint64_t Unit079::Mix(std::uint64_t value) const {
  std::uint64_t x = value ^ seed_;
  x ^= x >> 33;
  x *= 0xff51afd7ed558ccdULL;
  x ^= x >> 33;
  x *= 0xc4ceb9fe1a85ec53ULL;
  x ^= x >> 33;
  x ^= ballast_lib079::all(x);
  x ^= lib041_checksum(x);
  x ^= lib051_checksum(x);
  x ^= lib061_checksum(x);
  return x;
}

std::string Unit079::Describe() const {
  std::ostringstream out;
  out << "Unit079(seed=" << seed_ << ")";
  out << "+" << Unit041(seed_).Describe();
  return out.str();
}

std::vector<std::uint64_t> Unit079::Fold(const std::vector<std::uint64_t>& input) const {
  std::vector<std::uint64_t> result;
  result.reserve(input.size());
  for (std::uint64_t v : input) {
    result.push_back(Mix(v));
  }
  std::sort(result.begin(), result.end());
  return result;
}

std::uint64_t lib079_checksum(std::uint64_t value) {
  Unit079 instance(0x8ff3a718b7e479a2ULL);
  return instance.Mix(value);
}

}  // namespace kilncache_bench
