// Generated by scripts/gen_bazel_fixture.py. Do not edit.
#ifndef KILNCACHE_BENCH_LIB010_H_
#define KILNCACHE_BENCH_LIB010_H_

#include <cstdint>
#include <string>
#include <vector>

namespace kilncache_bench {

// A deliberately ordinary interface. The work here is to give the compiler
// something to do, not to model anything.
class Unit010 {
 public:
  explicit Unit010(std::uint64_t seed);

  std::uint64_t Mix(std::uint64_t value) const;
  std::string Describe() const;
  std::vector<std::uint64_t> Fold(const std::vector<std::uint64_t>& input) const;

 private:
  std::uint64_t seed_;
};

std::uint64_t lib010_checksum(std::uint64_t value);

}  // namespace kilncache_bench

#endif  // KILNCACHE_BENCH_LIB010_H_
