// Generated by scripts/gen_bazel_fixture.py. Do not edit.
#include "src/lib084.h"

#include "src/lib039.h"
#include "src/lib051.h"
#include "src/lib056.h"
#include <algorithm>
#include <array>
#include <numeric>
#include <sstream>

namespace ballast_lib084 {

template <int N, typename T>
struct Chain {
  static T apply(T x) {
    return Chain<N - 1, T>::apply(x * 6364136223846793005ULL + N) ^ (x >> 7);
  }
};
template <typename T>
struct Chain<0, T> {
  static T apply(T x) { return x; }
};

template <int Tag>
struct Tagged {
  std::uint64_t v;
  std::array<std::uint64_t, 4> pad;
};

template <int Tag>
std::uint64_t sortmix(std::uint64_t x) {
  std::array<Tagged<Tag>, 24> a{};
  for (int i = 0; i < 24; ++i) {
    a[i].v = Chain<8, std::uint64_t>::apply(x + i + Tag);
  }
  std::sort(a.begin(), a.end(),
            [](const Tagged<Tag>& p, const Tagged<Tag>& q) { return p.v < q.v; });
  return a[0].v ^ a[23].v;
}

std::uint64_t f0(std::uint64_t x) { return sortmix<0>(x) + 2005041972ULL; }
std::uint64_t f1(std::uint64_t x) { return sortmix<1>(x) + 3573690503ULL; }
std::uint64_t f2(std::uint64_t x) { return sortmix<2>(x) + 1268892699ULL; }
std::uint64_t f3(std::uint64_t x) { return sortmix<3>(x) + 716199808ULL; }
std::uint64_t f4(std::uint64_t x) { return sortmix<4>(x) + 1302851993ULL; }
std::uint64_t f5(std::uint64_t x) { return sortmix<5>(x) + 3524426046ULL; }
std::uint64_t f6(std::uint64_t x) { return sortmix<6>(x) + 4181095574ULL; }
std::uint64_t f7(std::uint64_t x) { return sortmix<7>(x) + 3421471468ULL; }
std::uint64_t f8(std::uint64_t x) { return sortmix<8>(x) + 4109518032ULL; }
std::uint64_t f9(std::uint64_t x) { return sortmix<9>(x) + 2501772573ULL; }
std::uint64_t f10(std::uint64_t x) { return sortmix<10>(x) + 959425808ULL; }
std::uint64_t f11(std::uint64_t x) { return sortmix<11>(x) + 1269325714ULL; }
std::uint64_t f12(std::uint64_t x) { return sortmix<12>(x) + 1342782821ULL; }
std::uint64_t f13(std::uint64_t x) { return sortmix<13>(x) + 2837800076ULL; }
std::uint64_t f14(std::uint64_t x) { return sortmix<14>(x) + 2804192127ULL; }
std::uint64_t f15(std::uint64_t x) { return sortmix<15>(x) + 2342646799ULL; }
std::uint64_t f16(std::uint64_t x) { return sortmix<16>(x) + 1837396497ULL; }
std::uint64_t f17(std::uint64_t x) { return sortmix<17>(x) + 1788042982ULL; }
std::uint64_t f18(std::uint64_t x) { return sortmix<18>(x) + 2654668808ULL; }
std::uint64_t f19(std::uint64_t x) { return sortmix<19>(x) + 3011840439ULL; }
std::uint64_t f20(std::uint64_t x) { return sortmix<20>(x) + 275128248ULL; }
std::uint64_t f21(std::uint64_t x) { return sortmix<21>(x) + 1458762461ULL; }
std::uint64_t f22(std::uint64_t x) { return sortmix<22>(x) + 339133681ULL; }
std::uint64_t f23(std::uint64_t x) { return sortmix<23>(x) + 1240782631ULL; }
std::uint64_t f24(std::uint64_t x) { return sortmix<24>(x) + 4238297462ULL; }
std::uint64_t f25(std::uint64_t x) { return sortmix<25>(x) + 2767128794ULL; }
std::uint64_t f26(std::uint64_t x) { return sortmix<26>(x) + 1168463293ULL; }
std::uint64_t f27(std::uint64_t x) { return sortmix<27>(x) + 2759796283ULL; }
std::uint64_t f28(std::uint64_t x) { return sortmix<28>(x) + 2749370005ULL; }
std::uint64_t f29(std::uint64_t x) { return sortmix<29>(x) + 63713282ULL; }
std::uint64_t f30(std::uint64_t x) { return sortmix<30>(x) + 2414243153ULL; }
std::uint64_t f31(std::uint64_t x) { return sortmix<31>(x) + 712560816ULL; }
std::uint64_t f32(std::uint64_t x) { return sortmix<32>(x) + 3802284759ULL; }
std::uint64_t f33(std::uint64_t x) { return sortmix<33>(x) + 1502584318ULL; }
std::uint64_t f34(std::uint64_t x) { return sortmix<34>(x) + 7958934ULL; }
std::uint64_t f35(std::uint64_t x) { return sortmix<35>(x) + 2495446069ULL; }
std::uint64_t f36(std::uint64_t x) { return sortmix<36>(x) + 934409387ULL; }
std::uint64_t f37(std::uint64_t x) { return sortmix<37>(x) + 3764149145ULL; }
std::uint64_t f38(std::uint64_t x) { return sortmix<38>(x) + 2045309485ULL; }
std::uint64_t f39(std::uint64_t x) { return sortmix<39>(x) + 1807396191ULL; }

inline std::uint64_t all(std::uint64_t x) {
  std::uint64_t a = x;
  a ^= f0(a);
  a ^= f1(a);
  a ^= f2(a);
  a ^= f3(a);
  a ^= f4(a);
  a ^= f5(a);
  a ^= f6(a);
  a ^= f7(a);
  a ^= f8(a);
  a ^= f9(a);
  a ^= f10(a);
  a ^= f11(a);
  a ^= f12(a);
  a ^= f13(a);
  a ^= f14(a);
  a ^= f15(a);
  a ^= f16(a);
  a ^= f17(a);
  a ^= f18(a);
  a ^= f19(a);
  a ^= f20(a);
  a ^= f21(a);
  a ^= f22(a);
  a ^= f23(a);
  a ^= f24(a);
  a ^= f25(a);
  a ^= f26(a);
  a ^= f27(a);
  a ^= f28(a);
  a ^= f29(a);
  a ^= f30(a);
  a ^= f31(a);
  a ^= f32(a);
  a ^= f33(a);
  a ^= f34(a);
  a ^= f35(a);
  a ^= f36(a);
  a ^= f37(a);
  a ^= f38(a);
  a ^= f39(a);
  return a;
}

}  // namespace ballast_lib084


namespace kilncache_bench {

Unit084::Unit084(std::uint64_t seed) : seed_(seed ^ 0x60183bf49a64eb98ULL) {}

std::uint64_t Unit084::Mix(std::uint64_t value) const {
  std::uint64_t x = value ^ seed_;
  x ^= x >> 33;
  x *= 0xff51afd7ed558ccdULL;
  x ^= x >> 33;
  x *= 0xc4ceb9fe1a85ec53ULL;
  x ^= x >> 33;
  x ^= ballast_lib084::all(x);
  x ^= lib039_checksum(x);
  x ^= lib051_checksum(x);
  x ^= lib056_checksum(x);
  return x;
}

std::string Unit084::Describe() const {
  std::ostringstream out;
  out << "Unit084(seed=" << seed_ << ")";
  out << "+" << Unit039(seed_).Describe();
  return out.str();
}

std::vector<std::uint64_t> Unit084::Fold(const std::vector<std::uint64_t>& input) const {
  std::vector<std::uint64_t> result;
  result.reserve(input.size());
  for (std::uint64_t v : input) {
    result.push_back(Mix(v));
  }
  std::sort(result.begin(), result.end());
  return result;
}

std::uint64_t lib084_checksum(std::uint64_t value) {
  Unit084 instance(0x60183bf49a64eb98ULL);
  return instance.Mix(value);
}

}  // namespace kilncache_bench
