// Generated by scripts/gen_bazel_fixture.py. Do not edit.
#include "src/lib051.h"

#include "src/lib015.h"
#include <algorithm>
#include <array>
#include <numeric>
#include <sstream>

namespace ballast_lib051 {

template <int N, typename T>
struct Chain {
  static T apply(T x) {
    return Chain<N - 1, T>::apply(x * 6364136223846793005ULL + N) ^ (x >> 7);
  }
};
template <typename T>
struct Chain<0, T> {
  static T apply(T x) { return x; }
};

template <int Tag>
struct Tagged {
  std::uint64_t v;
  std::array<std::uint64_t, 4> pad;
};

template <int Tag>
std::uint64_t sortmix(std::uint64_t x) {
  std::array<Tagged<Tag>, 24> a{};
  for (int i = 0; i < 24; ++i) {
    a[i].v = Chain<8, std::uint64_t>::apply(x + i + Tag);
  }
  std::sort(a.begin(), a.end(),
            [](const Tagged<Tag>& p, const Tagged<Tag>& q) { return p.v < q.v; });
  return a[0].v ^ a[23].v;
}

std::uint64_t f0(std::uint64_t x) { return sortmix<0>(x) + 784181459ULL; }
std::uint64_t f1(std::uint64_t x) { return sortmix<1>(x) + 1287150553ULL; }
std::uint64_t f2(std::uint64_t x) { return sortmix<2>(x) + 1438702858ULL; }
std::uint64_t f3(std::uint64_t x) { return sortmix<3>(x) + 2066236946ULL; }
std::uint64_t f4(std::uint64_t x) { return sortmix<4>(x) + 3450059310ULL; }
std::uint64_t f5(std::uint64_t x) { return sortmix<5>(x) + 2499864045ULL; }
std::uint64_t f6(std::uint64_t x) { return sortmix<6>(x) + 2878961792ULL; }
std::uint64_t f7(std::uint64_t x) { return sortmix<7>(x) + 2076065945ULL; }
std::uint64_t f8(std::uint64_t x) { return sortmix<8>(x) + 1892739194ULL; }
std::uint64_t f9(std::uint64_t x) { return sortmix<9>(x) + 726228544ULL; }
std::uint64_t f10(std::uint64_t x) { return sortmix<10>(x) + 3340280779ULL; }
std::uint64_t f11(std::uint64_t x) { return sortmix<11>(x) + 3026087023ULL; }
std::uint64_t f12(std::uint64_t x) { return sortmix<12>(x) + 1786698982ULL; }
std::uint64_t f13(std::uint64_t x) { return sortmix<13>(x) + 3493879981ULL; }
std::uint64_t f14(std::uint64_t x) { return sortmix<14>(x) + 1147198727ULL; }
std::uint64_t f15(std::uint64_t x) { return sortmix<15>(x) + 750176825ULL; }
std::uint64_t f16(std::uint64_t x) { return sortmix<16>(x) + 2864547003ULL; }
std::uint64_t f17(std::uint64_t x) { return sortmix<17>(x) + 4282183586ULL; }
std::uint64_t f18(std::uint64_t x) { return sortmix<18>(x) + 277808505ULL; }
std::uint64_t f19(std::uint64_t x) { return sortmix<19>(x) + 3656584890ULL; }
std::uint64_t f20(std::uint64_t x) { return sortmix<20>(x) + 2153259349ULL; }
std::uint64_t f21(std::uint64_t x) { return sortmix<21>(x) + 4199302882ULL; }
std::uint64_t f22(std::uint64_t x) { return sortmix<22>(x) + 3379762756ULL; }
std::uint64_t f23(std::uint64_t x) { return sortmix<23>(x) + 1382409872ULL; }
std::uint64_t f24(std::uint64_t x) { return sortmix<24>(x) + 3019284041ULL; }
std::uint64_t f25(std::uint64_t x) { return sortmix<25>(x) + 2868929105ULL; }
std::uint64_t f26(std::uint64_t x) { return sortmix<26>(x) + 1357426614ULL; }
std::uint64_t f27(std::uint64_t x) { return sortmix<27>(x) + 658277555ULL; }
std::uint64_t f28(std::uint64_t x) { return sortmix<28>(x) + 2893183022ULL; }
std::uint64_t f29(std::uint64_t x) { return sortmix<29>(x) + 2129392678ULL; }
std::uint64_t f30(std::uint64_t x) { return sortmix<30>(x) + 1394539938ULL; }
std::uint64_t f31(std::uint64_t x) { return sortmix<31>(x) + 2941395488ULL; }
std::uint64_t f32(std::uint64_t x) { return sortmix<32>(x) + 1690575929ULL; }
std::uint64_t f33(std::uint64_t x) { return sortmix<33>(x) + 2994253771ULL; }
std::uint64_t f34(std::uint64_t x) { return sortmix<34>(x) + 1282898769ULL; }
std::uint64_t f35(std::uint64_t x) { return sortmix<35>(x) + 131056039ULL; }
std::uint64_t f36(std::uint64_t x) { return sortmix<36>(x) + 1589250102ULL; }
std::uint64_t f37(std::uint64_t x) { return sortmix<37>(x) + 4253182362ULL; }
std::uint64_t f38(std::uint64_t x) { return sortmix<38>(x) + 1353617448ULL; }
std::uint64_t f39(std::uint64_t x) { return sortmix<39>(x) + 2794413781ULL; }

inline std::uint64_t all(std::uint64_t x) {
  std::uint64_t a = x;
  a ^= f0(a);
  a ^= f1(a);
  a ^= f2(a);
  a ^= f3(a);
  a ^= f4(a);
  a ^= f5(a);
  a ^= f6(a);
  a ^= f7(a);
  a ^= f8(a);
  a ^= f9(a);
  a ^= f10(a);
  a ^= f11(a);
  a ^= f12(a);
  a ^= f13(a);
  a ^= f14(a);
  a ^= f15(a);
  a ^= f16(a);
  a ^= f17(a);
  a ^= f18(a);
  a ^= f19(a);
  a ^= f20(a);
  a ^= f21(a);
  a ^= f22(a);
  a ^= f23(a);
  a ^= f24(a);
  a ^= f25(a);
  a ^= f26(a);
  a ^= f27(a);
  a ^= f28(a);
  a ^= f29(a);
  a ^= f30(a);
  a ^= f31(a);
  a ^= f32(a);
  a ^= f33(a);
  a ^= f34(a);
  a ^= f35(a);
  a ^= f36(a);
  a ^= f37(a);
  a ^= f38(a);
  a ^= f39(a);
  return a;
}

}  // namespace ballast_lib051


namespace kilncache_bench {

Unit051::Unit051(std::uint64_t seed) : seed_(seed ^ 0x484861dc7670442eULL) {}

std::uint64_t Unit051::Mix(std::uint64_t value) const {
  std::uint64_t x = value ^ seed_;
  x ^= x >> 33;
  x *= 0xff51afd7ed558ccdULL;
  x ^= x >> 33;
  x *= 0xc4ceb9fe1a85ec53ULL;
  x ^= x >> 33;
  x ^= ballast_lib051::all(x);
  x ^= lib015_checksum(x);
  return x;
}

std::string Unit051::Describe() const {
  std::ostringstream out;
  out << "Unit051(seed=" << seed_ << ")";
  out << "+" << Unit015(seed_).Describe();
  return out.str();
}

std::vector<std::uint64_t> Unit051::Fold(const std::vector<std::uint64_t>& input) const {
  std::vector<std::uint64_t> result;
  result.reserve(input.size());
  for (std::uint64_t v : input) {
    result.push_back(Mix(v));
  }
  std::sort(result.begin(), result.end());
  return result;
}

std::uint64_t lib051_checksum(std::uint64_t value) {
  Unit051 instance(0x484861dc7670442eULL);
  return instance.Mix(value);
}

}  // namespace kilncache_bench
