// Generated by scripts/gen_bazel_fixture.py. Do not edit.
#include "src/lib036.h"

#include "src/lib015.h"
#include "src/lib022.h"
#include <algorithm>
#include <array>
#include <numeric>
#include <sstream>

namespace ballast_lib036 {

template <int N, typename T>
struct Chain {
  static T apply(T x) {
    return Chain<N - 1, T>::apply(x * 6364136223846793005ULL + N) ^ (x >> 7);
  }
};
template <typename T>
struct Chain<0, T> {
  static T apply(T x) { return x; }
};

template <int Tag>
struct Tagged {
  std::uint64_t v;
  std::array<std::uint64_t, 4> pad;
};

template <int Tag>
std::uint64_t sortmix(std::uint64_t x) {
  std::array<Tagged<Tag>, 24> a{};
  for (int i = 0; i < 24; ++i) {
    a[i].v = Chain<8, std::uint64_t>::apply(x + i + Tag);
  }
  std::sort(a.begin(), a.end(),
            [](const Tagged<Tag>& p, const Tagged<Tag>& q) { return p.v < q.v; });
  return a[0].v ^ a[23].v;
}

std::uint64_t f0(std::uint64_t x) { return sortmix<0>(x) + 2169915024ULL; }
std::uint64_t f1(std::uint64_t x) { return sortmix<1>(x) + 718163842ULL; }
std::uint64_t f2(std::uint64_t x) { return sortmix<2>(x) + 3275080220ULL; }
std::uint64_t f3(std::uint64_t x) { return sortmix<3>(x) + 1409346619ULL; }
std::uint64_t f4(std::uint64_t x) { return sortmix<4>(x) + 3260680486ULL; }
std::uint64_t f5(std::uint64_t x) { return sortmix<5>(x) + 1558885759ULL; }
std::uint64_t f6(std::uint64_t x) { return sortmix<6>(x) + 3402884491ULL; }
std::uint64_t f7(std::uint64_t x) { return sortmix<7>(x) + 2086407486ULL; }
std::uint64_t f8(std::uint64_t x) { return sortmix<8>(x) + 2742625959ULL; }
std::uint64_t f9(std::uint64_t x) { return sortmix<9>(x) + 3769228345ULL; }
std::uint64_t f10(std::uint64_t x) { return sortmix<10>(x) + 2473436962ULL; }
std::uint64_t f11(std::uint64_t x) { return sortmix<11>(x) + 2599887704ULL; }
std::uint64_t f12(std::uint64_t x) { return sortmix<12>(x) + 1897399985ULL; }
std::uint64_t f13(std::uint64_t x) { return sortmix<13>(x) + 3694567508ULL; }
std::uint64_t f14(std::uint64_t x) { return sortmix<14>(x) + 219857787ULL; }
std::uint64_t f15(std::uint64_t x) { return sortmix<15>(x) + 4174916861ULL; }
std::uint64_t f16(std::uint64_t x) { return sortmix<16>(x) + 212859521ULL; }
std::uint64_t f17(std::uint64_t x) { return sortmix<17>(x) + 455533074ULL; }
std::uint64_t f18(std::uint64_t x) { return sortmix<18>(x) + 175400262ULL; }
std::uint64_t f19(std::uint64_t x) { return sortmix<19>(x) + 1500391704ULL; }
std::uint64_t f20(std::uint64_t x) { return sortmix<20>(x) + 3402704850ULL; }
std::uint64_t f21(std::uint64_t x) { return sortmix<21>(x) + 3031235734ULL; }
std::uint64_t f22(std::uint64_t x) { return sortmix<22>(x) + 4013778857ULL; }
std::uint64_t f23(std::uint64_t x) { return sortmix<23>(x) + 794968127ULL; }
std::uint64_t f24(std::uint64_t x) { return sortmix<24>(x) + 945091093ULL; }
std::uint64_t f25(std::uint64_t x) { return sortmix<25>(x) + 2208667458ULL; }
std::uint64_t f26(std::uint64_t x) { return sortmix<26>(x) + 2648598144ULL; }
std::uint64_t f27(std::uint64_t x) { return sortmix<27>(x) + 4051000358ULL; }
std::uint64_t f28(std::uint64_t x) { return sortmix<28>(x) + 2301201683ULL; }
std::uint64_t f29(std::uint64_t x) { return sortmix<29>(x) + 1832336828ULL; }
std::uint64_t f30(std::uint64_t x) { return sortmix<30>(x) + 2303867225ULL; }
std::uint64_t f31(std::uint64_t x) { return sortmix<31>(x) + 2392654652ULL; }
std::uint64_t f32(std::uint64_t x) { return sortmix<32>(x) + 2971430644ULL; }
std::uint64_t f33(std::uint64_t x) { return sortmix<33>(x) + 73156502ULL; }
std::uint64_t f34(std::uint64_t x) { return sortmix<34>(x) + 2580708020ULL; }
std::uint64_t f35(std::uint64_t x) { return sortmix<35>(x) + 703350638ULL; }
std::uint64_t f36(std::uint64_t x) { return sortmix<36>(x) + 2423436873ULL; }
std::uint64_t f37(std::uint64_t x) { return sortmix<37>(x) + 4198081449ULL; }
std::uint64_t f38(std::uint64_t x) { return sortmix<38>(x) + 1768131298ULL; }
std::uint64_t f39(std::uint64_t x) { return sortmix<39>(x) + 2786419616ULL; }

inline std::uint64_t all(std::uint64_t x) {
  std::uint64_t a = x;
  a ^= f0(a);
  a ^= f1(a);
  a ^= f2(a);
  a ^= f3(a);
  a ^= f4(a);
  a ^= f5(a);
  a ^= f6(a);
  a ^= f7(a);
  a ^= f8(a);
  a ^= f9(a);
  a ^= f10(a);
  a ^= f11(a);
  a ^= f12(a);
  a ^= f13(a);
  a ^= f14(a);
  a ^= f15(a);
  a ^= f16(a);
  a ^= f17(a);
  a ^= f18(a);
  a ^= f19(a);
  a ^= f20(a);
  a ^= f21(a);
  a ^= f22(a);
  a ^= f23(a);
  a ^= f24(a);
  a ^= f25(a);
  a ^= f26(a);
  a ^= f27(a);
  a ^= f28(a);
  a ^= f29(a);
  a ^= f30(a);
  a ^= f31(a);
  a ^= f32(a);
  a ^= f33(a);
  a ^= f34(a);
  a ^= f35(a);
  a ^= f36(a);
  a ^= f37(a);
  a ^= f38(a);
  a ^= f39(a);
  return a;
}

}  // namespace ballast_lib036


namespace kilncache_bench {

Unit036::Unit036(std::uint64_t seed) : seed_(seed ^ 0x1f639ed18baa45a9ULL) {}

std::uint64_t Unit036::Mix(std::uint64_t value) const {
  std::uint64_t x = value ^ seed_;
  x ^= x >> 33;
  x *= 0xff51afd7ed558ccdULL;
  x ^= x >> 33;
  x *= 0xc4ceb9fe1a85ec53ULL;
  x ^= x >> 33;
  x ^= ballast_lib036::all(x);
  x ^= lib015_checksum(x);
  x ^= lib022_checksum(x);
  return x;
}

std::string Unit036::Describe() const {
  std::ostringstream out;
  out << "Unit036(seed=" << seed_ << ")";
  out << "+" << Unit015(seed_).Describe();
  return out.str();
}

std::vector<std::uint64_t> Unit036::Fold(const std::vector<std::uint64_t>& input) const {
  std::vector<std::uint64_t> result;
  result.reserve(input.size());
  for (std::uint64_t v : input) {
    result.push_back(Mix(v));
  }
  std::sort(result.begin(), result.end());
  return result;
}

std::uint64_t lib036_checksum(std::uint64_t value) {
  Unit036 instance(0x1f639ed18baa45a9ULL);
  return instance.Mix(value);
}

}  // namespace kilncache_bench
