// Generated by scripts/gen_bazel_fixture.py. Do not edit.
#include "src/lib177.h"

#include "src/lib144.h"
#include "src/lib154.h"
#include <algorithm>
#include <array>
#include <numeric>
#include <sstream>

namespace ballast_lib177 {

template <int N, typename T>
struct Chain {
  static T apply(T x) {
    return Chain<N - 1, T>::apply(x * 6364136223846793005ULL + N) ^ (x >> 7);
  }
};
template <typename T>
struct Chain<0, T> {
  static T apply(T x) { return x; }
};

template <int Tag>
struct Tagged {
  std::uint64_t v;
  std::array<std::uint64_t, 4> pad;
};

template <int Tag>
std::uint64_t sortmix(std::uint64_t x) {
  std::array<Tagged<Tag>, 24> a{};
  for (int i = 0; i < 24; ++i) {
    a[i].v = Chain<8, std::uint64_t>::apply(x + i + Tag);
  }
  std::sort(a.begin(), a.end(),
            [](const Tagged<Tag>& p, const Tagged<Tag>& q) { return p.v < q.v; });
  return a[0].v ^ a[23].v;
}

std::uint64_t f0(std::uint64_t x) { return sortmix<0>(x) + 1003634666ULL; }
std::uint64_t f1(std::uint64_t x) { return sortmix<1>(x) + 1325121986ULL; }
std::uint64_t f2(std::uint64_t x) { return sortmix<2>(x) + 2102445502ULL; }
std::uint64_t f3(std::uint64_t x) { return sortmix<3>(x) + 4284246841ULL; }
std::uint64_t f4(std::uint64_t x) { return sortmix<4>(x) + 2005382009ULL; }
std::uint64_t f5(std::uint64_t x) { return sortmix<5>(x) + 1043721804ULL; }
std::uint64_t f6(std::uint64_t x) { return sortmix<6>(x) + 715906139ULL; }
std::uint64_t f7(std::uint64_t x) { return sortmix<7>(x) + 1180949437ULL; }
std::uint64_t f8(std::uint64_t x) { return sortmix<8>(x) + 846452562ULL; }
std::uint64_t f9(std::uint64_t x) { return sortmix<9>(x) + 3016483067ULL; }
std::uint64_t f10(std::uint64_t x) { return sortmix<10>(x) + 3568180890ULL; }
std::uint64_t f11(std::uint64_t x) { return sortmix<11>(x) + 2301236365ULL; }
std::uint64_t f12(std::uint64_t x) { return sortmix<12>(x) + 420474599ULL; }
std::uint64_t f13(std::uint64_t x) { return sortmix<13>(x) + 3335999206ULL; }
std::uint64_t f14(std::uint64_t x) { return sortmix<14>(x) + 392229156ULL; }
std::uint64_t f15(std::uint64_t x) { return sortmix<15>(x) + 3703731609ULL; }
std::uint64_t f16(std::uint64_t x) { return sortmix<16>(x) + 3590744584ULL; }
std::uint64_t f17(std::uint64_t x) { return sortmix<17>(x) + 2534620138ULL; }
std::uint64_t f18(std::uint64_t x) { return sortmix<18>(x) + 2727963863ULL; }
std::uint64_t f19(std::uint64_t x) { return sortmix<19>(x) + 3621088499ULL; }
std::uint64_t f20(std::uint64_t x) { return sortmix<20>(x) + 1837333809ULL; }
std::uint64_t f21(std::uint64_t x) { return sortmix<21>(x) + 3200161298ULL; }
std::uint64_t f22(std::uint64_t x) { return sortmix<22>(x) + 4198925901ULL; }
std::uint64_t f23(std::uint64_t x) { return sortmix<23>(x) + 1330963306ULL; }
std::uint64_t f24(std::uint64_t x) { return sortmix<24>(x) + 856762870ULL; }
std::uint64_t f25(std::uint64_t x) { return sortmix<25>(x) + 1984952697ULL; }
std::uint64_t f26(std::uint64_t x) { return sortmix<26>(x) + 3266261269ULL; }
std::uint64_t f27(std::uint64_t x) { return sortmix<27>(x) + 3578572955ULL; }
std::uint64_t f28(std::uint64_t x) { return sortmix<28>(x) + 3164349986ULL; }
std::uint64_t f29(std::uint64_t x) { return sortmix<29>(x) + 2358554556ULL; }
std::uint64_t f30(std::uint64_t x) { return sortmix<30>(x) + 600012410ULL; }
std::uint64_t f31(std::uint64_t x) { return sortmix<31>(x) + 3491146544ULL; }
std::uint64_t f32(std::uint64_t x) { return sortmix<32>(x) + 2490342770ULL; }
std::uint64_t f33(std::uint64_t x) { return sortmix<33>(x) + 4108928458ULL; }
std::uint64_t f34(std::uint64_t x) { return sortmix<34>(x) + 694613014ULL; }
std::uint64_t f35(std::uint64_t x) { return sortmix<35>(x) + 1842652146ULL; }
std::uint64_t f36(std::uint64_t x) { return sortmix<36>(x) + 472019842ULL; }
std::uint64_t f37(std::uint64_t x) { return sortmix<37>(x) + 2007675291ULL; }
std::uint64_t f38(std::uint64_t x) { return sortmix<38>(x) + 2124977479ULL; }
std::uint64_t f39(std::uint64_t x) { return sortmix<39>(x) + 546683956ULL; }

inline std::uint64_t all(std::uint64_t x) {
  std::uint64_t a = x;
  a ^= f0(a);
  a ^= f1(a);
  a ^= f2(a);
  a ^= f3(a);
  a ^= f4(a);
  a ^= f5(a);
  a ^= f6(a);
  a ^= f7(a);
  a ^= f8(a);
  a ^= f9(a);
  a ^= f10(a);
  a ^= f11(a);
  a ^= f12(a);
  a ^= f13(a);
  a ^= f14(a);
  a ^= f15(a);
  a ^= f16(a);
  a ^= f17(a);
  a ^= f18(a);
  a ^= f19(a);
  a ^= f20(a);
  a ^= f21(a);
  a ^= f22(a);
  a ^= f23(a);
  a ^= f24(a);
  a ^= f25(a);
  a ^= f26(a);
  a ^= f27(a);
  a ^= f28(a);
  a ^= f29(a);
  a ^= f30(a);
  a ^= f31(a);
  a ^= f32(a);
  a ^= f33(a);
  a ^= f34(a);
  a ^= f35(a);
  a ^= f36(a);
  a ^= f37(a);
  a ^= f38(a);
  a ^= f39(a);
  return a;
}

}  // namespace ballast_lib177


namespace kilncache_bench {

Unit177::Unit177(std::uint64_t seed) : seed_(seed ^ 0x9f048c9e678684a8ULL) {}

std::uint64_t Unit177::Mix(std::uint64_t value) const {
  std::uint64_t x = value ^ seed_;
  x ^= x >> 33;
  x *= 0xff51afd7ed558ccdULL;
  x ^= x >> 33;
  x *= 0xc4ceb9fe1a85ec53ULL;
  x ^= x >> 33;
  x ^= ballast_lib177::all(x);
  x ^= lib144_checksum(x);
  x ^= lib154_checksum(x);
  return x;
}

std::string Unit177::Describe() const {
  std::ostringstream out;
  out << "Unit177(seed=" << seed_ << ")";
  out << "+" << Unit144(seed_).Describe();
  return out.str();
}

std::vector<std::uint64_t> Unit177::Fold(const std::vector<std::uint64_t>& input) const {
  std::vector<std::uint64_t> result;
  result.reserve(input.size());
  for (std::uint64_t v : input) {
    result.push_back(Mix(v));
  }
  std::sort(result.begin(), result.end());
  return result;
}

std::uint64_t lib177_checksum(std::uint64_t value) {
  Unit177 instance(0x9f048c9e678684a8ULL);
  return instance.Mix(value);
}

}  // namespace kilncache_bench
