// Generated by scripts/gen_bazel_fixture.py. Do not edit.
#include "src/lib119.h"

#include "src/lib075.h"
#include <algorithm>
#include <array>
#include <numeric>
#include <sstream>

namespace ballast_lib119 {

template <int N, typename T>
struct Chain {
  static T apply(T x) {
    return Chain<N - 1, T>::apply(x * 6364136223846793005ULL + N) ^ (x >> 7);
  }
};
template <typename T>
struct Chain<0, T> {
  static T apply(T x) { return x; }
};

template <int Tag>
struct Tagged {
  std::uint64_t v;
  std::array<std::uint64_t, 4> pad;
};

template <int Tag>
std::uint64_t sortmix(std::uint64_t x) {
  std::array<Tagged<Tag>, 24> a{};
  for (int i = 0; i < 24; ++i) {
    a[i].v = Chain<8, std::uint64_t>::apply(x + i + Tag);
  }
  std::sort(a.begin(), a.end(),
            [](const Tagged<Tag>& p, const Tagged<Tag>& q) { return p.v < q.v; });
  return a[0].v ^ a[23].v;
}

std::uint64_t f0(std::uint64_t x) { return sortmix<0>(x) + 651076781ULL; }
std::uint64_t f1(std::uint64_t x) { return sortmix<1>(x) + 4070953145ULL; }
std::uint64_t f2(std::uint64_t x) { return sortmix<2>(x) + 1481206817ULL; }
std::uint64_t f3(std::uint64_t x) { return sortmix<3>(x) + 1895796999ULL; }
std::uint64_t f4(std::uint64_t x) { return sortmix<4>(x) + 3953136690ULL; }
std::uint64_t f5(std::uint64_t x) { return sortmix<5>(x) + 2176555824ULL; }
std::uint64_t f6(std::uint64_t x) { return sortmix<6>(x) + 3772135017ULL; }
std::uint64_t f7(std::uint64_t x) { return sortmix<7>(x) + 1493068588ULL; }
std::uint64_t f8(std::uint64_t x) { return sortmix<8>(x) + 1946062957ULL; }
std::uint64_t f9(std::uint64_t x) { return sortmix<9>(x) + 155189328ULL; }
std::uint64_t f10(std::uint64_t x) { return sortmix<10>(x) + 3328156426ULL; }
std::uint64_t f11(std::uint64_t x) { return sortmix<11>(x) + 498973403ULL; }
std::uint64_t f12(std::uint64_t x) { return sortmix<12>(x) + 797389750ULL; }
std::uint64_t f13(std::uint64_t x) { return sortmix<13>(x) + 3299094159ULL; }
std::uint64_t f14(std::uint64_t x) { return sortmix<14>(x) + 1442286174ULL; }
std::uint64_t f15(std::uint64_t x) { return sortmix<15>(x) + 2302408227ULL; }
std::uint64_t f16(std::uint64_t x) { return sortmix<16>(x) + 263798479ULL; }
std::uint64_t f17(std::uint64_t x) { return sortmix<17>(x) + 735098835ULL; }
std::uint64_t f18(std::uint64_t x) { return sortmix<18>(x) + 3253887286ULL; }
std::uint64_t f19(std::uint64_t x) { return sortmix<19>(x) + 478541801ULL; }
std::uint64_t f20(std::uint64_t x) { return sortmix<20>(x) + 3571151184ULL; }
std::uint64_t f21(std::uint64_t x) { return sortmix<21>(x) + 24323892ULL; }
std::uint64_t f22(std::uint64_t x) { return sortmix<22>(x) + 4264797893ULL; }
std::uint64_t f23(std::uint64_t x) { return sortmix<23>(x) + 4161993263ULL; }
std::uint64_t f24(std::uint64_t x) { return sortmix<24>(x) + 2392671092ULL; }
std::uint64_t f25(std::uint64_t x) { return sortmix<25>(x) + 1912787603ULL; }
std::uint64_t f26(std::uint64_t x) { return sortmix<26>(x) + 3424908822ULL; }
std::uint64_t f27(std::uint64_t x) { return sortmix<27>(x) + 602059070ULL; }
std::uint64_t f28(std::uint64_t x) { return sortmix<28>(x) + 739807639ULL; }
std::uint64_t f29(std::uint64_t x) { return sortmix<29>(x) + 1913691799ULL; }
std::uint64_t f30(std::uint64_t x) { return sortmix<30>(x) + 500366667ULL; }
std::uint64_t f31(std::uint64_t x) { return sortmix<31>(x) + 507840078ULL; }
std::uint64_t f32(std::uint64_t x) { return sortmix<32>(x) + 2370668801ULL; }
std::uint64_t f33(std::uint64_t x) { return sortmix<33>(x) + 3342433847ULL; }
std::uint64_t f34(std::uint64_t x) { return sortmix<34>(x) + 1980045106ULL; }
std::uint64_t f35(std::uint64_t x) { return sortmix<35>(x) + 3637772607ULL; }
std::uint64_t f36(std::uint64_t x) { return sortmix<36>(x) + 56451877ULL; }
std::uint64_t f37(std::uint64_t x) { return sortmix<37>(x) + 3595439953ULL; }
std::uint64_t f38(std::uint64_t x) { return sortmix<38>(x) + 2163181617ULL; }
std::uint64_t f39(std::uint64_t x) { return sortmix<39>(x) + 4288153990ULL; }

inline std::uint64_t all(std::uint64_t x) {
  std::uint64_t a = x;
  a ^= f0(a);
  a ^= f1(a);
  a ^= f2(a);
  a ^= f3(a);
  a ^= f4(a);
  a ^= f5(a);
  a ^= f6(a);
  a ^= f7(a);
  a ^= f8(a);
  a ^= f9(a);
  a ^= f10(a);
  a ^= f11(a);
  a ^= f12(a);
  a ^= f13(a);
  a ^= f14(a);
  a ^= f15(a);
  a ^= f16(a);
  a ^= f17(a);
  a ^= f18(a);
  a ^= f19(a);
  a ^= f20(a);
  a ^= f21(a);
  a ^= f22(a);
  a ^= f23(a);
  a ^= f24(a);
  a ^= f25(a);
  a ^= f26(a);
  a ^= f27(a);
  a ^= f28(a);
  a ^= f29(a);
  a ^= f30(a);
  a ^= f31(a);
  a ^= f32(a);
  a ^= f33(a);
  a ^= f34(a);
  a ^= f35(a);
  a ^= f36(a);
  a ^= f37(a);
  a ^= f38(a);
  a ^= f39(a);
  return a;
}

}  // namespace ballast_lib119


namespace kilncache_bench {

Unit119::Unit119(std::uint64_t seed) : seed_(seed ^ 0x212d7a3a68cc8348ULL) {}

std::uint64_t Unit119::Mix(std::uint64_t value) const {
  std::uint64_t x = value ^ seed_;
  x ^= x >> 33;
  x *= 0xff51afd7ed558ccdULL;
  x ^= x >> 33;
  x *= 0xc4ceb9fe1a85ec53ULL;
  x ^= x >> 33;
  x ^= ballast_lib119::all(x);
  x ^= lib075_checksum(x);
  return x;
}

std::string Unit119::Describe() const {
  std::ostringstream out;
  out << "Unit119(seed=" << seed_ << ")";
  out << "+" << Unit075(seed_).Describe();
  return out.str();
}

std::vector<std::uint64_t> Unit119::Fold(const std::vector<std::uint64_t>& input) const {
  std::vector<std::uint64_t> result;
  result.reserve(input.size());
  for (std::uint64_t v : input) {
    result.push_back(Mix(v));
  }
  std::sort(result.begin(), result.end());
  return result;
}

std::uint64_t lib119_checksum(std::uint64_t value) {
  Unit119 instance(0x212d7a3a68cc8348ULL);
  return instance.Mix(value);
}

}  // namespace kilncache_bench
