// Generated by scripts/gen_bazel_fixture.py. Do not edit.
#include "src/lib134.h"

#include "src/lib082.h"
#include "src/lib103.h"
#include <algorithm>
#include <array>
#include <numeric>
#include <sstream>

namespace ballast_lib134 {

template <int N, typename T>
struct Chain {
  static T apply(T x) {
    return Chain<N - 1, T>::apply(x * 6364136223846793005ULL + N) ^ (x >> 7);
  }
};
template <typename T>
struct Chain<0, T> {
  static T apply(T x) { return x; }
};

template <int Tag>
struct Tagged {
  std::uint64_t v;
  std::array<std::uint64_t, 4> pad;
};

template <int Tag>
std::uint64_t sortmix(std::uint64_t x) {
  std::array<Tagged<Tag>, 24> a{};
  for (int i = 0; i < 24; ++i) {
    a[i].v = Chain<8, std::uint64_t>::apply(x + i + Tag);
  }
  std::sort(a.begin(), a.end(),
            [](const Tagged<Tag>& p, const Tagged<Tag>& q) { return p.v < q.v; });
  return a[0].v ^ a[23].v;
}

std::uint64_t f0(std::uint64_t x) { return sortmix<0>(x) + 2643121088ULL; }
std::uint64_t f1(std::uint64_t x) { return sortmix<1>(x) + 3106597073ULL; }
std::uint64_t f2(std::uint64_t x) { return sortmix<2>(x) + 3260816054ULL; }
std::uint64_t f3(std::uint64_t x) { return sortmix<3>(x) + 458464019ULL; }
std::uint64_t f4(std::uint64_t x) { return sortmix<4>(x) + 3062880165ULL; }
std::uint64_t f5(std::uint64_t x) { return sortmix<5>(x) + 3622099241ULL; }
std::uint64_t f6(std::uint64_t x) { return sortmix<6>(x) + 680866629ULL; }
std::uint64_t f7(std::uint64_t x) { return sortmix<7>(x) + 2874869670ULL; }
std::uint64_t f8(std::uint64_t x) { return sortmix<8>(x) + 1370929656ULL; }
std::uint64_t f9(std::uint64_t x) { return sortmix<9>(x) + 3068891652ULL; }
std::uint64_t f10(std::uint64_t x) { return sortmix<10>(x) + 656033682ULL; }
std::uint64_t f11(std::uint64_t x) { return sortmix<11>(x) + 3324688686ULL; }
std::uint64_t f12(std::uint64_t x) { return sortmix<12>(x) + 3891930940ULL; }
std::uint64_t f13(std::uint64_t x) { return sortmix<13>(x) + 1070931471ULL; }
std::uint64_t f14(std::uint64_t x) { return sortmix<14>(x) + 3695911907ULL; }
std::uint64_t f15(std::uint64_t x) { return sortmix<15>(x) + 224995250ULL; }
std::uint64_t f16(std::uint64_t x) { return sortmix<16>(x) + 999370438ULL; }
std::uint64_t f17(std::uint64_t x) { return sortmix<17>(x) + 2603411601ULL; }
std::uint64_t f18(std::uint64_t x) { return sortmix<18>(x) + 324640044ULL; }
std::uint64_t f19(std::uint64_t x) { return sortmix<19>(x) + 288749604ULL; }
std::uint64_t f20(std::uint64_t x) { return sortmix<20>(x) + 1754402769ULL; }
std::uint64_t f21(std::uint64_t x) { return sortmix<21>(x) + 141072216ULL; }
std::uint64_t f22(std::uint64_t x) { return sortmix<22>(x) + 1113695148ULL; }
std::uint64_t f23(std::uint64_t x) { return sortmix<23>(x) + 2051226931ULL; }
std::uint64_t f24(std::uint64_t x) { return sortmix<24>(x) + 801617620ULL; }
std::uint64_t f25(std::uint64_t x) { return sortmix<25>(x) + 830451561ULL; }
std::uint64_t f26(std::uint64_t x) { return sortmix<26>(x) + 2794473862ULL; }
std::uint64_t f27(std::uint64_t x) { return sortmix<27>(x) + 3344799337ULL; }
std::uint64_t f28(std::uint64_t x) { return sortmix<28>(x) + 3040983344ULL; }
std::uint64_t f29(std::uint64_t x) { return sortmix<29>(x) + 2397302230ULL; }
std::uint64_t f30(std::uint64_t x) { return sortmix<30>(x) + 937055490ULL; }
std::uint64_t f31(std::uint64_t x) { return sortmix<31>(x) + 2365503743ULL; }
std::uint64_t f32(std::uint64_t x) { return sortmix<32>(x) + 2792006471ULL; }
std::uint64_t f33(std::uint64_t x) { return sortmix<33>(x) + 3209442192ULL; }
std::uint64_t f34(std::uint64_t x) { return sortmix<34>(x) + 781881441ULL; }
std::uint64_t f35(std::uint64_t x) { return sortmix<35>(x) + 860504568ULL; }
std::uint64_t f36(std::uint64_t x) { return sortmix<36>(x) + 4131633291ULL; }
std::uint64_t f37(std::uint64_t x) { return sortmix<37>(x) + 4056962696ULL; }
std::uint64_t f38(std::uint64_t x) { return sortmix<38>(x) + 3159336713ULL; }
std::uint64_t f39(std::uint64_t x) { return sortmix<39>(x) + 881560582ULL; }

inline std::uint64_t all(std::uint64_t x) {
  std::uint64_t a = x;
  a ^= f0(a);
  a ^= f1(a);
  a ^= f2(a);
  a ^= f3(a);
  a ^= f4(a);
  a ^= f5(a);
  a ^= f6(a);
  a ^= f7(a);
  a ^= f8(a);
  a ^= f9(a);
  a ^= f10(a);
  a ^= f11(a);
  a ^= f12(a);
  a ^= f13(a);
  a ^= f14(a);
  a ^= f15(a);
  a ^= f16(a);
  a ^= f17(a);
  a ^= f18(a);
  a ^= f19(a);
  a ^= f20(a);
  a ^= f21(a);
  a ^= f22(a);
  a ^= f23(a);
  a ^= f24(a);
  a ^= f25(a);
  a ^= f26(a);
  a ^= f27(a);
  a ^= f28(a);
  a ^= f29(a);
  a ^= f30(a);
  a ^= f31(a);
  a ^= f32(a);
  a ^= f33(a);
  a ^= f34(a);
  a ^= f35(a);
  a ^= f36(a);
  a ^= f37(a);
  a ^= f38(a);
  a ^= f39(a);
  return a;
}

}  // namespace ballast_lib134


namespace kilncache_bench {

Unit134::Unit134(std::uint64_t seed) : seed_(seed ^ 0x4d550d1646f58d5bULL) {}

std::uint64_t Unit134::Mix(std::uint64_t value) const {
  std::uint64_t x = value ^ seed_;
  x ^= x >> 33;
  x *= 0xff51afd7ed558ccdULL;
  x ^= x >> 33;
  x *= 0xc4ceb9fe1a85ec53ULL;
  x ^= x >> 33;
  x ^= ballast_lib134::all(x);
  x ^= lib082_checksum(x);
  x ^= lib103_checksum(x);
  return x;
}

std::string Unit134::Describe() const {
  std::ostringstream out;
  out << "Unit134(seed=" << seed_ << ")";
  out << "+" << Unit082(seed_).Describe();
  return out.str();
}

std::vector<std::uint64_t> Unit134::Fold(const std::vector<std::uint64_t>& input) const {
  std::vector<std::uint64_t> result;
  result.reserve(input.size());
  for (std::uint64_t v : input) {
    result.push_back(Mix(v));
  }
  std::sort(result.begin(), result.end());
  return result;
}

std::uint64_t lib134_checksum(std::uint64_t value) {
  Unit134 instance(0x4d550d1646f58d5bULL);
  return instance.Mix(value);
}

}  // namespace kilncache_bench
