// Generated by scripts/gen_bazel_fixture.py. Do not edit.
#include "src/lib164.h"

#include "src/lib119.h"
#include "src/lib123.h"
#include <algorithm>
#include <array>
#include <numeric>
#include <sstream>

namespace ballast_lib164 {

template <int N, typename T>
struct Chain {
  static T apply(T x) {
    return Chain<N - 1, T>::apply(x * 6364136223846793005ULL + N) ^ (x >> 7);
  }
};
template <typename T>
struct Chain<0, T> {
  static T apply(T x) { return x; }
};

template <int Tag>
struct Tagged {
  std::uint64_t v;
  std::array<std::uint64_t, 4> pad;
};

template <int Tag>
std::uint64_t sortmix(std::uint64_t x) {
  std::array<Tagged<Tag>, 24> a{};
  for (int i = 0; i < 24; ++i) {
    a[i].v = Chain<8, std::uint64_t>::apply(x + i + Tag);
  }
  std::sort(a.begin(), a.end(),
            [](const Tagged<Tag>& p, const Tagged<Tag>& q) { return p.v < q.v; });
  return a[0].v ^ a[23].v;
}

std::uint64_t f0(std::uint64_t x) { return sortmix<0>(x) + 1405943315ULL; }
std::uint64_t f1(std::uint64_t x) { return sortmix<1>(x) + 3260057871ULL; }
std::uint64_t f2(std::uint64_t x) { return sortmix<2>(x) + 3433369506ULL; }
std::uint64_t f3(std::uint64_t x) { return sortmix<3>(x) + 618597453ULL; }
std::uint64_t f4(std::uint64_t x) { return sortmix<4>(x) + 2356324864ULL; }
std::uint64_t f5(std::uint64_t x) { return sortmix<5>(x) + 3604025219ULL; }
std::uint64_t f6(std::uint64_t x) { return sortmix<6>(x) + 1822233956ULL; }
std::uint64_t f7(std::uint64_t x) { return sortmix<7>(x) + 2689545704ULL; }
std::uint64_t f8(std::uint64_t x) { return sortmix<8>(x) + 335343039ULL; }
std::uint64_t f9(std::uint64_t x) { return sortmix<9>(x) + 1928281744ULL; }
std::uint64_t f10(std::uint64_t x) { return sortmix<10>(x) + 3783250379ULL; }
std::uint64_t f11(std::uint64_t x) { return sortmix<11>(x) + 207184202ULL; }
std::uint64_t f12(std::uint64_t x) { return sortmix<12>(x) + 3554384547ULL; }
std::uint64_t f13(std::uint64_t x) { return sortmix<13>(x) + 3620609818ULL; }
std::uint64_t f14(std::uint64_t x) { return sortmix<14>(x) + 3240442377ULL; }
std::uint64_t f15(std::uint64_t x) { return sortmix<15>(x) + 272181408ULL; }
std::uint64_t f16(std::uint64_t x) { return sortmix<16>(x) + 1383660033ULL; }
std::uint64_t f17(std::uint64_t x) { return sortmix<17>(x) + 1130448493ULL; }
std::uint64_t f18(std::uint64_t x) { return sortmix<18>(x) + 2354547873ULL; }
std::uint64_t f19(std::uint64_t x) { return sortmix<19>(x) + 3686050543ULL; }
std::uint64_t f20(std::uint64_t x) { return sortmix<20>(x) + 2644149876ULL; }
std::uint64_t f21(std::uint64_t x) { return sortmix<21>(x) + 1801360244ULL; }
std::uint64_t f22(std::uint64_t x) { return sortmix<22>(x) + 2240583266ULL; }
std::uint64_t f23(std::uint64_t x) { return sortmix<23>(x) + 1885381314ULL; }
std::uint64_t f24(std::uint64_t x) { return sortmix<24>(x) + 2647987105ULL; }
std::uint64_t f25(std::uint64_t x) { return sortmix<25>(x) + 2658799039ULL; }
std::uint64_t f26(std::uint64_t x) { return sortmix<26>(x) + 1134622024ULL; }
std::uint64_t f27(std::uint64_t x) { return sortmix<27>(x) + 893567926ULL; }
std::uint64_t f28(std::uint64_t x) { return sortmix<28>(x) + 1360583523ULL; }
std::uint64_t f29(std::uint64_t x) { return sortmix<29>(x) + 1481622190ULL; }
std::uint64_t f30(std::uint64_t x) { return sortmix<30>(x) + 850004761ULL; }
std::uint64_t f31(std::uint64_t x) { return sortmix<31>(x) + 2176872717ULL; }
std::uint64_t f32(std::uint64_t x) { return sortmix<32>(x) + 3613608450ULL; }
std::uint64_t f33(std::uint64_t x) { return sortmix<33>(x) + 2703867786ULL; }
std::uint64_t f34(std::uint64_t x) { return sortmix<34>(x) + 1779689833ULL; }
std::uint64_t f35(std::uint64_t x) { return sortmix<35>(x) + 3916274543ULL; }
std::uint64_t f36(std::uint64_t x) { return sortmix<36>(x) + 2980997569ULL; }
std::uint64_t f37(std::uint64_t x) { return sortmix<37>(x) + 3293589436ULL; }
std::uint64_t f38(std::uint64_t x) { return sortmix<38>(x) + 3968437524ULL; }
std::uint64_t f39(std::uint64_t x) { return sortmix<39>(x) + 3324206021ULL; }

inline std::uint64_t all(std::uint64_t x) {
  std::uint64_t a = x;
  a ^= f0(a);
  a ^= f1(a);
  a ^= f2(a);
  a ^= f3(a);
  a ^= f4(a);
  a ^= f5(a);
  a ^= f6(a);
  a ^= f7(a);
  a ^= f8(a);
  a ^= f9(a);
  a ^= f10(a);
  a ^= f11(a);
  a ^= f12(a);
  a ^= f13(a);
  a ^= f14(a);
  a ^= f15(a);
  a ^= f16(a);
  a ^= f17(a);
  a ^= f18(a);
  a ^= f19(a);
  a ^= f20(a);
  a ^= f21(a);
  a ^= f22(a);
  a ^= f23(a);
  a ^= f24(a);
  a ^= f25(a);
  a ^= f26(a);
  a ^= f27(a);
  a ^= f28(a);
  a ^= f29(a);
  a ^= f30(a);
  a ^= f31(a);
  a ^= f32(a);
  a ^= f33(a);
  a ^= f34(a);
  a ^= f35(a);
  a ^= f36(a);
  a ^= f37(a);
  a ^= f38(a);
  a ^= f39(a);
  return a;
}

}  // namespace ballast_lib164


namespace kilncache_bench {

Unit164::Unit164(std::uint64_t seed) : seed_(seed ^ 0xa3753697cb957d25ULL) {}

std::uint64_t Unit164::Mix(std::uint64_t value) const {
  std::uint64_t x = value ^ seed_;
  x ^= x >> 33;
  x *= 0xff51afd7ed558ccdULL;
  x ^= x >> 33;
  x *= 0xc4ceb9fe1a85ec53ULL;
  x ^= x >> 33;
  x ^= ballast_lib164::all(x);
  x ^= lib119_checksum(x);
  x ^= lib123_checksum(x);
  return x;
}

std::string Unit164::Describe() const {
  std::ostringstream out;
  out << "Unit164(seed=" << seed_ << ")";
  out << "+" << Unit119(seed_).Describe();
  return out.str();
}

std::vector<std::uint64_t> Unit164::Fold(const std::vector<std::uint64_t>& input) const {
  std::vector<std::uint64_t> result;
  result.reserve(input.size());
  for (std::uint64_t v : input) {
    result.push_back(Mix(v));
  }
  std::sort(result.begin(), result.end());
  return result;
}

std::uint64_t lib164_checksum(std::uint64_t value) {
  Unit164 instance(0xa3753697cb957d25ULL);
  return instance.Mix(value);
}

}  // namespace kilncache_bench
