// Generated by scripts/gen_bazel_fixture.py. Do not edit.
#include "src/lib239.h"

#include "src/lib191.h"
#include <algorithm>
#include <array>
#include <numeric>
#include <sstream>

namespace ballast_lib239 {

template <int N, typename T>
struct Chain {
  static T apply(T x) {
    return Chain<N - 1, T>::apply(x * 6364136223846793005ULL + N) ^ (x >> 7);
  }
};
template <typename T>
struct Chain<0, T> {
  static T apply(T x) { return x; }
};

template <int Tag>
struct Tagged {
  std::uint64_t v;
  std::array<std::uint64_t, 4> pad;
};

template <int Tag>
std::uint64_t sortmix(std::uint64_t x) {
  std::array<Tagged<Tag>, 24> a{};
  for (int i = 0; i < 24; ++i) {
    a[i].v = Chain<8, std::uint64_t>::apply(x + i + Tag);
  }
  std::sort(a.begin(), a.end(),
            [](const Tagged<Tag>& p, const Tagged<Tag>& q) { return p.v < q.v; });
  return a[0].v ^ a[23].v;
}

std::uint64_t f0(std::uint64_t x) { return sortmix<0>(x) + 1700360169ULL; }
std::uint64_t f1(std::uint64_t x) { return sortmix<1>(x) + 2888630122ULL; }
std::uint64_t f2(std::uint64_t x) { return sortmix<2>(x) + 1219413127ULL; }
std::uint64_t f3(std::uint64_t x) { return sortmix<3>(x) + 3210485782ULL; }
std::uint64_t f4(std::uint64_t x) { return sortmix<4>(x) + 1389446010ULL; }
std::uint64_t f5(std::uint64_t x) { return sortmix<5>(x) + 645258769ULL; }
std::uint64_t f6(std::uint64_t x) { return sortmix<6>(x) + 2180888780ULL; }
std::uint64_t f7(std::uint64_t x) { return sortmix<7>(x) + 193905223ULL; }
std::uint64_t f8(std::uint64_t x) { return sortmix<8>(x) + 4206083127ULL; }
std::uint64_t f9(std::uint64_t x) { return sortmix<9>(x) + 1136406410ULL; }
std::uint64_t f10(std::uint64_t x) { return sortmix<10>(x) + 1551692156ULL; }
std::uint64_t f11(std::uint64_t x) { return sortmix<11>(x) + 2921556833ULL; }
std::uint64_t f12(std::uint64_t x) { return sortmix<12>(x) + 1172229973ULL; }
std::uint64_t f13(std::uint64_t x) { return sortmix<13>(x) + 2231703483ULL; }
std::uint64_t f14(std::uint64_t x) { return sortmix<14>(x) + 1846217576ULL; }
std::uint64_t f15(std::uint64_t x) { return sortmix<15>(x) + 3432970697ULL; }
std::uint64_t f16(std::uint64_t x) { return sortmix<16>(x) + 3090799844ULL; }
std::uint64_t f17(std::uint64_t x) { return sortmix<17>(x) + 3539928825ULL; }
std::uint64_t f18(std::uint64_t x) { return sortmix<18>(x) + 654015920ULL; }
std::uint64_t f19(std::uint64_t x) { return sortmix<19>(x) + 2140580373ULL; }
std::uint64_t f20(std::uint64_t x) { return sortmix<20>(x) + 784654482ULL; }
std::uint64_t f21(std::uint64_t x) { return sortmix<21>(x) + 3386001048ULL; }
std::uint64_t f22(std::uint64_t x) { return sortmix<22>(x) + 1529998940ULL; }
std::uint64_t f23(std::uint64_t x) { return sortmix<23>(x) + 184434202ULL; }
std::uint64_t f24(std::uint64_t x) { return sortmix<24>(x) + 2898892313ULL; }
std::uint64_t f25(std::uint64_t x) { return sortmix<25>(x) + 2387592111ULL; }
std::uint64_t f26(std::uint64_t x) { return sortmix<26>(x) + 3355877522ULL; }
std::uint64_t f27(std::uint64_t x) { return sortmix<27>(x) + 3032821309ULL; }
std::uint64_t f28(std::uint64_t x) { return sortmix<28>(x) + 3811105514ULL; }
std::uint64_t f29(std::uint64_t x) { return sortmix<29>(x) + 2464428671ULL; }
std::uint64_t f30(std::uint64_t x) { return sortmix<30>(x) + 1367580866ULL; }
std::uint64_t f31(std::uint64_t x) { return sortmix<31>(x) + 3482140851ULL; }
std::uint64_t f32(std::uint64_t x) { return sortmix<32>(x) + 1994710241ULL; }
std::uint64_t f33(std::uint64_t x) { return sortmix<33>(x) + 3070541428ULL; }
std::uint64_t f34(std::uint64_t x) { return sortmix<34>(x) + 1787056703ULL; }
std::uint64_t f35(std::uint64_t x) { return sortmix<35>(x) + 1072547742ULL; }
std::uint64_t f36(std::uint64_t x) { return sortmix<36>(x) + 3677213609ULL; }
std::uint64_t f37(std::uint64_t x) { return sortmix<37>(x) + 3694978742ULL; }
std::uint64_t f38(std::uint64_t x) { return sortmix<38>(x) + 2539679427ULL; }
std::uint64_t f39(std::uint64_t x) { return sortmix<39>(x) + 3824277921ULL; }

inline std::uint64_t all(std::uint64_t x) {
  std::uint64_t a = x;
  a ^= f0(a);
  a ^= f1(a);
  a ^= f2(a);
  a ^= f3(a);
  a ^= f4(a);
  a ^= f5(a);
  a ^= f6(a);
  a ^= f7(a);
  a ^= f8(a);
  a ^= f9(a);
  a ^= f10(a);
  a ^= f11(a);
  a ^= f12(a);
  a ^= f13(a);
  a ^= f14(a);
  a ^= f15(a);
  a ^= f16(a);
  a ^= f17(a);
  a ^= f18(a);
  a ^= f19(a);
  a ^= f20(a);
  a ^= f21(a);
  a ^= f22(a);
  a ^= f23(a);
  a ^= f24(a);
  a ^= f25(a);
  a ^= f26(a);
  a ^= f27(a);
  a ^= f28(a);
  a ^= f29(a);
  a ^= f30(a);
  a ^= f31(a);
  a ^= f32(a);
  a ^= f33(a);
  a ^= f34(a);
  a ^= f35(a);
  a ^= f36(a);
  a ^= f37(a);
  a ^= f38(a);
  a ^= f39(a);
  return a;
}

}  // namespace ballast_lib239


namespace kilncache_bench {

Unit239::Unit239(std::uint64_t seed) : seed_(seed ^ 0xbcfe6e75e3ee74dbULL) {}

std::uint64_t Unit239::Mix(std::uint64_t value) const {
  std::uint64_t x = value ^ seed_;
  x ^= x >> 33;
  x *= 0xff51afd7ed558ccdULL;
  x ^= x >> 33;
  x *= 0xc4ceb9fe1a85ec53ULL;
  x ^= x >> 33;
  x ^= ballast_lib239::all(x);
  x ^= lib191_checksum(x);
  return x;
}

std::string Unit239::Describe() const {
  std::ostringstream out;
  out << "Unit239(seed=" << seed_ << ")";
  out << "+" << Unit191(seed_).Describe();
  return out.str();
}

std::vector<std::uint64_t> Unit239::Fold(const std::vector<std::uint64_t>& input) const {
  std::vector<std::uint64_t> result;
  result.reserve(input.size());
  for (std::uint64_t v : input) {
    result.push_back(Mix(v));
  }
  std::sort(result.begin(), result.end());
  return result;
}

std::uint64_t lib239_checksum(std::uint64_t value) {
  Unit239 instance(0xbcfe6e75e3ee74dbULL);
  return instance.Mix(value);
}

}  // namespace kilncache_bench
