// Generated by scripts/gen_bazel_fixture.py. Do not edit.
#include "src/lib241.h"

#include "src/lib200.h"
#include "src/lib203.h"
#include "src/lib208.h"
#include <algorithm>
#include <array>
#include <numeric>
#include <sstream>

namespace ballast_lib241 {

template <int N, typename T>
struct Chain {
  static T apply(T x) {
    return Chain<N - 1, T>::apply(x * 6364136223846793005ULL + N) ^ (x >> 7);
  }
};
template <typename T>
struct Chain<0, T> {
  static T apply(T x) { return x; }
};

template <int Tag>
struct Tagged {
  std::uint64_t v;
  std::array<std::uint64_t, 4> pad;
};

template <int Tag>
std::uint64_t sortmix(std::uint64_t x) {
  std::array<Tagged<Tag>, 24> a{};
  for (int i = 0; i < 24; ++i) {
    a[i].v = Chain<8, std::uint64_t>::apply(x + i + Tag);
  }
  std::sort(a.begin(), a.end(),
            [](const Tagged<Tag>& p, const Tagged<Tag>& q) { return p.v < q.v; });
  return a[0].v ^ a[23].v;
}

std::uint64_t f0(std::uint64_t x) { return sortmix<0>(x) + 1439799881ULL; }
std::uint64_t f1(std::uint64_t x) { return sortmix<1>(x) + 926559156ULL; }
std::uint64_t f2(std::uint64_t x) { return sortmix<2>(x) + 2210181359ULL; }
std::uint64_t f3(std::uint64_t x) { return sortmix<3>(x) + 2600959655ULL; }
std::uint64_t f4(std::uint64_t x) { return sortmix<4>(x) + 4262573962ULL; }
std::uint64_t f5(std::uint64_t x) { return sortmix<5>(x) + 3700018542ULL; }
std::uint64_t f6(std::uint64_t x) { return sortmix<6>(x) + 4130495139ULL; }
std::uint64_t f7(std::uint64_t x) { return sortmix<7>(x) + 3790208637ULL; }
std::uint64_t f8(std::uint64_t x) { return sortmix<8>(x) + 1263880335ULL; }
std::uint64_t f9(std::uint64_t x) { return sortmix<9>(x) + 185746681ULL; }
std::uint64_t f10(std::uint64_t x) { return sortmix<10>(x) + 1750104380ULL; }
std::uint64_t f11(std::uint64_t x) { return sortmix<11>(x) + 3621694130ULL; }
std::uint64_t f12(std::uint64_t x) { return sortmix<12>(x) + 2265045205ULL; }
std::uint64_t f13(std::uint64_t x) { return sortmix<13>(x) + 3841521309ULL; }
std::uint64_t f14(std::uint64_t x) { return sortmix<14>(x) + 707361619ULL; }
std::uint64_t f15(std::uint64_t x) { return sortmix<15>(x) + 3998239506ULL; }
std::uint64_t f16(std::uint64_t x) { return sortmix<16>(x) + 1783134699ULL; }
std::uint64_t f17(std::uint64_t x) { return sortmix<17>(x) + 536128070ULL; }
std::uint64_t f18(std::uint64_t x) { return sortmix<18>(x) + 1676062280ULL; }
std::uint64_t f19(std::uint64_t x) { return sortmix<19>(x) + 4100332219ULL; }
std::uint64_t f20(std::uint64_t x) { return sortmix<20>(x) + 3123769304ULL; }
std::uint64_t f21(std::uint64_t x) { return sortmix<21>(x) + 3573021228ULL; }
std::uint64_t f22(std::uint64_t x) { return sortmix<22>(x) + 948962501ULL; }
std::uint64_t f23(std::uint64_t x) { return sortmix<23>(x) + 4267669565ULL; }
std::uint64_t f24(std::uint64_t x) { return sortmix<24>(x) + 2895390432ULL; }
std::uint64_t f25(std::uint64_t x) { return sortmix<25>(x) + 353144420ULL; }
std::uint64_t f26(std::uint64_t x) { return sortmix<26>(x) + 1007452584ULL; }
std::uint64_t f27(std::uint64_t x) { return sortmix<27>(x) + 1806758174ULL; }
std::uint64_t f28(std::uint64_t x) { return sortmix<28>(x) + 1780868194ULL; }
std::uint64_t f29(std::uint64_t x) { return sortmix<29>(x) + 944206624ULL; }
std::uint64_t f30(std::uint64_t x) { return sortmix<30>(x) + 1634288433ULL; }
std::uint64_t f31(std::uint64_t x) { return sortmix<31>(x) + 1809128411ULL; }
std::uint64_t f32(std::uint64_t x) { return sortmix<32>(x) + 3512209717ULL; }
std::uint64_t f33(std::uint64_t x) { return sortmix<33>(x) + 4121635582ULL; }
std::uint64_t f34(std::uint64_t x) { return sortmix<34>(x) + 1930715707ULL; }
std::uint64_t f35(std::uint64_t x) { return sortmix<35>(x) + 1365702136ULL; }
std::uint64_t f36(std::uint64_t x) { return sortmix<36>(x) + 1589500742ULL; }
std::uint64_t f37(std::uint64_t x) { return sortmix<37>(x) + 2697546854ULL; }
std::uint64_t f38(std::uint64_t x) { return sortmix<38>(x) + 1158579929ULL; }
std::uint64_t f39(std::uint64_t x) { return sortmix<39>(x) + 2527468385ULL; }

inline std::uint64_t all(std::uint64_t x) {
  std::uint64_t a = x;
  a ^= f0(a);
  a ^= f1(a);
  a ^= f2(a);
  a ^= f3(a);
  a ^= f4(a);
  a ^= f5(a);
  a ^= f6(a);
  a ^= f7(a);
  a ^= f8(a);
  a ^= f9(a);
  a ^= f10(a);
  a ^= f11(a);
  a ^= f12(a);
  a ^= f13(a);
  a ^= f14(a);
  a ^= f15(a);
  a ^= f16(a);
  a ^= f17(a);
  a ^= f18(a);
  a ^= f19(a);
  a ^= f20(a);
  a ^= f21(a);
  a ^= f22(a);
  a ^= f23(a);
  a ^= f24(a);
  a ^= f25(a);
  a ^= f26(a);
  a ^= f27(a);
  a ^= f28(a);
  a ^= f29(a);
  a ^= f30(a);
  a ^= f31(a);
  a ^= f32(a);
  a ^= f33(a);
  a ^= f34(a);
  a ^= f35(a);
  a ^= f36(a);
  a ^= f37(a);
  a ^= f38(a);
  a ^= f39(a);
  return a;
}

}  // namespace ballast_lib241


namespace kilncache_bench {

Unit241::Unit241(std::uint64_t seed) : seed_(seed ^ 0x4b7176d3b1f69975ULL) {}

std::uint64_t Unit241::Mix(std::uint64_t value) const {
  std::uint64_t x = value ^ seed_;
  x ^= x >> 33;
  x *= 0xff51afd7ed558ccdULL;
  x ^= x >> 33;
  x *= 0xc4ceb9fe1a85ec53ULL;
  x ^= x >> 33;
  x ^= ballast_lib241::all(x);
  x ^= lib200_checksum(x);
  x ^= lib203_checksum(x);
  x ^= lib208_checksum(x);
  return x;
}

std::string Unit241::Describe() const {
  std::ostringstream out;
  out << "Unit241(seed=" << seed_ << ")";
  out << "+" << Unit200(seed_).Describe();
  return out.str();
}

std::vector<std::uint64_t> Unit241::Fold(const std::vector<std::uint64_t>& input) const {
  std::vector<std::uint64_t> result;
  result.reserve(input.size());
  for (std::uint64_t v : input) {
    result.push_back(Mix(v));
  }
  std::sort(result.begin(), result.end());
  return result;
}

std::uint64_t lib241_checksum(std::uint64_t value) {
  Unit241 instance(0x4b7176d3b1f69975ULL);
  return instance.Mix(value);
}

}  // namespace kilncache_bench
