#!/usr/bin/env python3
"""Generate a deterministic Bazel C++ workspace for the end-to-end benchmark.

Shape of the graph: libraries are assigned to layers, and a library in layer N
depends on a small random sample of libraries in layer N-1. Binaries sit on top
and each link a handful of libraries from the upper layers.

Layering rather than a uniformly random DAG is deliberate. A random DAG over 280
nodes has a very short critical path and builds almost embarrassingly in
parallel, which is precisely the workload where a remote cache looks best and
tells you least. Layers give a depth that is comparable to a real project's, so
the measured saving reflects work that could not simply have been parallelised
away.

Every source file is generated from a seeded RNG, so the workspace is
byte-identical on every run: a cold build and a cache-served build compile the
same bytes, and a rebuild weeks later measures the cache rather than drift in
the workload.
"""

import argparse
import os
import random
import shutil
import textwrap

BAZEL_VERSION = "7.4.1"

MODULE_BAZEL = '''\
# Bzlmod module for the KilnCache benchmark fixture.
#
# Deliberately dependency-free: the point of this workspace is to compile a
# known quantity of C++, and every external dependency would add a download to
# the measured build and a version to drift.
module(
    name = "kilncache_bench",
    version = "1.0",
)
'''

BAZELRC = '''\
# Keep the output base on a local filesystem. This workspace may live on a
# Windows drive mounted into WSL, where Bazel's symlink and locking assumptions
# are both slow and unreliable.
startup --output_user_root=%OUTPUT_ROOT%

# Deterministic, comparable builds.
build --incompatible_strict_action_env
build --experimental_convenience_symlinks=ignore
common --enable_bzlmod

# C++ settings chosen so that compilation dominates and is reproducible.
build --cxxopt=-std=c++17
build --features=-supports_dynamic_linker

# Remote cache defaults. Override --remote_cache on the command line.
build:remote --remote_upload_local_results=true
build:remote --remote_timeout=120s
build:remote --experimental_remote_cache_async=false

# Fail loudly rather than silently falling back to local-only, so a benchmark
# run cannot quietly measure a build with no cache at all.
build:remote --remote_local_fallback=false
'''

BAZELIGNORE = ""

HEADER_TEMPLATE = '''\
// Generated by scripts/gen_bazel_fixture.py. Do not edit.
#ifndef KILNCACHE_BENCH_{GUARD}_H_
#define KILNCACHE_BENCH_{GUARD}_H_

#include <cstdint>
#include <string>
#include <vector>

namespace kilncache_bench {{

// A deliberately ordinary interface. The work here is to give the compiler
// something to do, not to model anything.
class {cls} {{
 public:
  explicit {cls}(std::uint64_t seed);

  std::uint64_t Mix(std::uint64_t value) const;
  std::string Describe() const;
  std::vector<std::uint64_t> Fold(const std::vector<std::uint64_t>& input) const;

 private:
  std::uint64_t seed_;
}};

std::uint64_t {fn}_checksum(std::uint64_t value);

}}  // namespace kilncache_bench

#endif  // KILNCACHE_BENCH_{GUARD}_H_
'''

# Compile-time ballast.
#
# Without this, each translation unit compiles in well under a tenth of a
# second, the whole 300-target build finishes in about seven seconds, and most
# of that is Bazel's own loading and analysis. Measuring a cache against that
# workload measures Bazel's startup, not the cache.
#
# The ballast is template instantiation rather than sheer line count because it
# costs the compiler real work *and* produces object files of a realistic size
# (a few hundred KiB), so the benchmark moves a realistic number of bytes
# through the cache as well as spending a realistic amount of CPU.
BALLAST_TEMPLATE = '''\
namespace ballast_{fn} {{

template <int N, typename T>
struct Chain {{
  static T apply(T x) {{
    return Chain<N - 1, T>::apply(x * 6364136223846793005ULL + N) ^ (x >> 7);
  }}
}};
template <typename T>
struct Chain<0, T> {{
  static T apply(T x) {{ return x; }}
}};

template <int Tag>
struct Tagged {{
  std::uint64_t v;
  std::array<std::uint64_t, 4> pad;
}};

template <int Tag>
std::uint64_t sortmix(std::uint64_t x) {{
  std::array<Tagged<Tag>, 24> a{{}};
  for (int i = 0; i < 24; ++i) {{
    a[i].v = Chain<{depth}, std::uint64_t>::apply(x + i + Tag);
  }}
  std::sort(a.begin(), a.end(),
            [](const Tagged<Tag>& p, const Tagged<Tag>& q) {{ return p.v < q.v; }});
  return a[0].v ^ a[23].v;
}}

{funcs}

inline std::uint64_t all(std::uint64_t x) {{
  std::uint64_t a = x;
{calls}
  return a;
}}

}}  // namespace ballast_{fn}
'''

SOURCE_HEAD = '''\
// Generated by scripts/gen_bazel_fixture.py. Do not edit.
#include "{header}"

{includes}
#include <algorithm>
#include <array>
#include <numeric>
#include <sstream>

{ballast}

namespace kilncache_bench {{

{cls}::{cls}(std::uint64_t seed) : seed_(seed ^ 0x{magic:016x}ULL) {{}}

std::uint64_t {cls}::Mix(std::uint64_t value) const {{
  std::uint64_t x = value ^ seed_;
  x ^= x >> 33;
  x *= 0xff51afd7ed558ccdULL;
  x ^= x >> 33;
  x *= 0xc4ceb9fe1a85ec53ULL;
  x ^= x >> 33;
  x ^= ballast_{fn}::all(x);
{dep_mix}
  return x;
}}

std::string {cls}::Describe() const {{
  std::ostringstream out;
  out << "{cls}(seed=" << seed_ << ")";
{dep_describe}
  return out.str();
}}

std::vector<std::uint64_t> {cls}::Fold(const std::vector<std::uint64_t>& input) const {{
  std::vector<std::uint64_t> result;
  result.reserve(input.size());
  for (std::uint64_t v : input) {{
    result.push_back(Mix(v));
  }}
  std::sort(result.begin(), result.end());
  return result;
}}

std::uint64_t {fn}_checksum(std::uint64_t value) {{
  {cls} instance(0x{magic:016x}ULL);
  return instance.Mix(value);
}}

}}  // namespace kilncache_bench
'''

BINARY_TEMPLATE = '''\
// Generated by scripts/gen_bazel_fixture.py. Do not edit.
#include <cstdint>
#include <cstdio>
#include <vector>

{includes}

int main(int argc, char** argv) {{
  std::uint64_t acc = static_cast<std::uint64_t>(argc);
  std::vector<std::uint64_t> input;
  for (int i = 0; i < 64; ++i) {{
    input.push_back(static_cast<std::uint64_t>(i) * 2654435761ULL);
  }}

{calls}

  std::printf("{name} checksum=%llu\\n", static_cast<unsigned long long>(acc));
  (void)argv;
  return 0;
}}
'''


def lib_name(i):
    return f"lib{i:03d}"


def bin_name(i):
    return f"bench{i:02d}"


def class_name(i):
    return f"Unit{i:03d}"


def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--libs", type=int, default=280)
    ap.add_argument("--bins", type=int, default=20)
    ap.add_argument("--out", required=True)
    ap.add_argument("--seed", type=int, default=20260920)
    ap.add_argument("--layers", type=int, default=8)
    ap.add_argument("--max-deps", type=int, default=3)
    # Ballast weight. 40 gives roughly a second of compile time per translation
    # unit on the development host and object files of a few hundred KiB, which
    # is what makes the end-to-end benchmark measure the cache rather than
    # Bazel's fixed overhead. Lower it for a quick smoke build.
    ap.add_argument("--weight", type=int, default=40)
    ap.add_argument("--chain-depth", type=int, default=8)
    args = ap.parse_args()

    rng = random.Random(args.seed)
    out = os.path.abspath(args.out)

    # Regenerate from scratch: a stale source file from a previous shape would
    # silently change the workload the benchmark measures.
    src_root = os.path.join(out, "src")
    if os.path.isdir(src_root):
        shutil.rmtree(src_root)

    # Assign libraries to layers.
    layers = [[] for _ in range(args.layers)]
    for i in range(args.libs):
        layers[i * args.layers // args.libs].append(i)

    deps = {}
    for depth, layer in enumerate(layers):
        for i in layer:
            if depth == 0:
                deps[i] = []
                continue
            pool = layers[depth - 1]
            k = min(len(pool), rng.randint(1, args.max_deps))
            deps[i] = sorted(rng.sample(pool, k))

    build_lines = [
        "# Generated by scripts/gen_bazel_fixture.py. Do not edit.",
        "#",
        f"# {args.libs} cc_library targets in {args.layers} layers plus {args.bins} cc_binary",
        "# targets. The layering gives the graph a realistic critical path; a flat",
        "# set of independent targets would parallelise away the very serialization",
        "# a remote cache is supposed to relieve.",
        "",
        'package(default_visibility = ["//visibility:public"])',
        "",
    ]

    for i in range(args.libs):
        name = lib_name(i)
        cls = class_name(i)
        guard = name.upper()
        header_path = f"src/{name}.h"
        source_path = f"src/{name}.cc"

        write(os.path.join(out, header_path),
              HEADER_TEMPLATE.format(GUARD=guard, cls=cls, fn=name))

        dep_includes = "\n".join(f'#include "src/{lib_name(d)}.h"' for d in deps[i])
        dep_mix = "\n".join(
            f"  x ^= {lib_name(d)}_checksum(x);" for d in deps[i]
        )
        dep_describe = "\n".join(
            f'  out << "+" << {class_name(d)}(seed_).Describe();' for d in deps[i][:1]
        )
        funcs = "\n".join(
            f"std::uint64_t f{j}(std::uint64_t x) {{ return sortmix<{j}>(x) + {rng.getrandbits(32)}ULL; }}"
            for j in range(args.weight)
        )
        calls = "\n".join(f"  a ^= f{j}(a);" for j in range(args.weight))
        ballast = BALLAST_TEMPLATE.format(
            fn=name, depth=args.chain_depth, funcs=funcs, calls=calls)

        write(os.path.join(out, source_path),
              SOURCE_HEAD.format(
                  header=header_path,
                  includes=dep_includes,
                  ballast=ballast,
                  cls=cls,
                  fn=name,
                  magic=rng.getrandbits(64),
                  dep_mix=dep_mix,
                  dep_describe=dep_describe,
              ))

        # Built by string concatenation rather than textwrap.dedent: dedent
        # strips the *common* indent, and an interpolated dependency list brings
        # its own (shallower) indentation into the block, so the common prefix
        # shrinks and the surrounding lines come out under-indented. Starlark
        # then rejects the file. Emitting the exact text is less clever and
        # cannot go wrong.
        dep_labels = "".join(f'        ":{lib_name(d)}",\n' for d in deps[i])
        build_lines.append(
            f'cc_library(\n'
            f'    name = "{name}",\n'
            f'    srcs = ["{source_path}"],\n'
            f'    hdrs = ["{header_path}"],\n'
            f'    deps = [\n{dep_labels}'
            f'    ],\n'
            f')\n'
        )

    top_layer = layers[-1] + layers[-2]
    for b in range(args.bins):
        name = bin_name(b)
        k = min(len(top_layer), rng.randint(3, 6))
        chosen = sorted(rng.sample(top_layer, k))
        includes = "\n".join(f'#include "src/{lib_name(d)}.h"' for d in chosen)
        calls = "\n".join(
            f"  acc ^= kilncache_bench::{lib_name(d)}_checksum(acc + {d});"
            for d in chosen
        )
        source_path = f"src/{name}.cc"
        write(os.path.join(out, source_path),
              BINARY_TEMPLATE.format(includes=includes, calls=calls, name=name))
        dep_labels = "".join(f'        ":{lib_name(d)}",\n' for d in chosen)
        build_lines.append(
            f'cc_binary(\n'
            f'    name = "{name}",\n'
            f'    srcs = ["{source_path}"],\n'
            f'    deps = [\n{dep_labels}'
            f'    ],\n'
            f')\n'
        )

    write(os.path.join(out, "BUILD.bazel"), "\n".join(build_lines) + "\n")
    write(os.path.join(out, "MODULE.bazel"), MODULE_BAZEL)
    write(os.path.join(out, ".bazelversion"), BAZEL_VERSION + "\n")
    write(os.path.join(out, ".bazelignore"), BAZELIGNORE)

    bazelrc = BAZELRC.replace(
        "%OUTPUT_ROOT%", os.path.join(os.path.expanduser("~"), ".cache", "bazel"))
    write(os.path.join(out, ".bazelrc"), bazelrc)

    write(os.path.join(out, "README.md"), textwrap.dedent(f'''\
        # bazel-cpp benchmark fixture

        Generated by `scripts/gen-bazel-fixture.sh`. **Do not edit by hand** —
        regenerating overwrites `src/`.

        - {args.libs} `cc_library` targets across {args.layers} layers
        - {args.bins} `cc_binary` targets
        - {args.libs + args.bins} targets total
        - Seed `{args.seed}`, so the sources are byte-identical on every
          generation and a build measured today is comparable to one measured
          next month.

        ## Build it

        ```bash
        cd fixtures/bazel-cpp
        bazel build //...                                        # local only
        bazel build //... --config=remote \\
              --remote_cache=http://localhost:8080               # through KilnCache
        ```

        ## Measure a cache-served rebuild

        ```bash
        bazel build //... --config=remote --remote_cache=http://localhost:8080
        bazel clean --expunge
        bazel build //... --config=remote --remote_cache=http://localhost:8080
        ```

        The second build should report remote cache hits for nearly every
        action. `scripts/bazel-bench.sh` automates this and records the raw
        numbers; nothing here is meant to be timed by hand.

        The C++ is deliberately dull. It exists to give the compiler a known,
        repeatable quantity of work with a realistic dependency depth.
        '''))

    total = args.libs + args.bins
    print(f"generated {total} targets ({args.libs} cc_library, {args.bins} cc_binary) in {out}")


if __name__ == "__main__":
    main()
